### ISSUE TITLE
Complex xemas in multiple-type definition result in compile error

### ISSUE THREAD

**Issue by smoes** [hrzndhrn/xema#139] opened 2020-10-22 19:33 UTC
The following example for multiple types is (more or less) from the Xema docs:
```
    Xema.new([:string, nil])
```
This seems to work fine, as long as you offer a simple atom/predefined type. 
When using complex types, the Xema cannot be compiled:
```
  # fails
  Xema.new([list(items: :string), nil]) 
```

I guess this is a bug, isn't it?

**Comment by smoes** [comment] 2020-10-22 19:49
Is the list syntax just syntactical sugar for `:one_of` ? 

That said, these seem to be essentially the same:

```
Xema.new([:string, nil])
Xema.new(one_of: [:string, nil])

```
while the latter works with any Xema, not just atoms:

```
# works
Xema.new(one_of: [list(items: :string), nil])
```

**Comment by NickNeck** [comment] 2020-10-22 19:53
No, this is not a bug. At the first position of schema or sub-schema `Xema` wants a type or multiple types. This types are `Xema` specific type and not types like in `@spec`. So possilbe types are `:any`, `:integer`, `:list`, `:number`, and so on, and `nil`, `true` and `false`.
For further restrictions you have to add keywords. So for a list of ints or a string or a nil:
```
iex(6)> s = Xema.new({[:string, :list, nil], items: :integer})
...
iex(7)> Xema.valid?(s, nil)
true
iex(8)> Xema.valid?(s, 55)
false
iex(9)> Xema.valid?(s, [55])
true
iex(10)> Xema.valid?(s, "foo")
true
```

**Comment by NickNeck** [comment] 2020-10-22 19:59
```
Xema.new([:string, nil])
Xema.new(one_of: [:string, nil])
```
Both schemata have the same behaviour, but are internally different schemata.
There are always several ways to reach the goal.

**Comment by smoes** [comment] 2020-10-22 20:00
Okay, but how would I model a multiple-type of two lists with different properties? E.g. I could have these two lists as I describe in the schema:

```
l1 = Xema.new {:list, items: {:integer, minimum: 1, maximum: 10}}
l2 = Xema.new {:list, items: {:integer, minimum: 10, maximum: 100}}
```
I believe you have reasons for why it is like that, but (at least to me) it is not very intuitive. Maybe I have to read the doc again to understand the distinction between a type and a xema. 

Thanks for your (very) fast response again :)

**Comment by NickNeck** [comment] 2020-10-22 20:15
The reason is actually always the similarity to JsonSchema. Just that `Xema` doesn't have an explicitly `type` keyword. But yes, constructing a schema can be hard sometimes. To be honest, before I answer here, I have to do it myself 
try out how it works.
Example:
```
'{"type": "integer"}' |> Jason.decode!() |> Xema.from_json_schema()
# is the same as
Xema.new(:integer)

'{"type": "integer", "minimum": 10}' |> Jason.decode!() |> Xema.from_json_schema()
# is the sam as
Xema.new({:integer, minimum: 10})
```
So, in `Xema.new` the tuple has always the form `{type, checks}`.

**Comment by NickNeck** [comment] 2020-10-22 20:20
And ...
```
l1 = Xema.new {:list, items: {:integer, minimum: 1, maximum: 10}}
l2 = Xema.new {:list, items: {:integer, minimum: 10, maximum: 100}}
s = Xema.new(any_of: [l1, l2])
Xema.valid?(s, [8,9]) # true
Xema.valid?(s, [8,19]) # true
Xema.valid?(s, [18,19]) # true
```

**Comment by NickNeck** [comment] 2020-10-23 06:10
`Xema` supports also another way to construct schemas
```elixir
iex(1)> defmodule MySchema do
...(1)>   use Xema
...(1)>
...(1)>   xema do
...(1)>     any(
...(1)>       any_of: [
...(1)>         list(items: integer(minimum: 1, maximum: 10)),
...(1)>         list(items: integer(minimum: 10, maximum: 100))
...(1)>       ]
...(1)>     )
...(1)>   end
...(1)> end
{:module, MySchema,
 <<70, 79, 82, 49, 0, 0, 15, 4, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 211,
   0, 0, 0, 22, 15, 69, 108, 105, 120, 105, 114, 46, 77, 121, 83, 99, 104, 101,
   109, 97, 8, 95, 95, 105, 110, 102, 111, ...>>, {:xema, 0}}
iex(2)> MySchema.valid?(1)
false
iex(3)> MySchema.valid?([])
true
iex(4)> MySchema.valid?([1])
true
iex(5)> MySchema.valid?([55])
true
iex(6)> MySchema.valid?([55, 11])
true
iex(7)> MySchema.valid?([55, 1])
false
```
I think the documentation for this has to be updated.

**Comment by smoes** [comment] 2020-10-23 07:42
Thanks! We are using the xema macro in our project. However, personally I'm a huge fan of using plain functions and values, since functions compose by nature, and Xemas are composable, too. Your library makes both possible, that's great!

**Comment by NickNeck** [comment] 2020-10-24 08:00
I hope I could help a little bit. For now, I will close this issue. Feel free to reopen this issue or create a new issue, if anything is not clear.

I am thinking about to add the combinator functions `any_of`, `all_of` and `one_of` to `Xema.Builder`, see PR #140  . What do you think?

**Closed by NickNeck** 2020-10-24 08:00 UTC

**Comment by smoes** [comment] 2020-10-26 07:50
It's clear now, thank you again for the fast, kind and patient support. 

Having these builder functions would definitely help :)
